### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by benogle** [santip/move-panes#2]
Uncaught TypeError: Cannot read property '0' of undefined

**Atom Version**: 0.159.0-e83784e
**System**: Mac OS X 10.9.5
**Thrown From**: [move-panes](https://github.com/santip/move-panes) package, v0.1.2
### Steps To Reproduce
1. Have only one pane open
2. Trigger move pane right
### Stack Trace

```
At /Users/ben/.atom/packages/move-panes/lib/move-panes.coffee:31

TypeError: Cannot read property '0' of undefined
  at Object.module.exports.move (/Users/ben/.atom/packages/move-panes/lib/move-panes.coffee:31:6)
  at Object.module.exports.moveLeft (/Users/ben/.atom/packages/move-panes/lib/move-panes.coffee:12:17)
  at atom-workspace.<anonymous> (/Users/ben/.atom/packages/move-panes/lib/move-panes.coffee:5:60)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```

/cc @atom/core

**Comment by jipiboily** [comment]
Getting the same, just in case someone was wondering if it was a problem only for one person.

**Comment by Trudko** [comment]
+ 1

**Comment by timobleeker** [comment]
+1
Would expect it to either do nothing or open a new pane and move the current pane.

**Comment by auguststurm** [comment]
+1 to expecting it to create a new pane... It did the move pane so well I just assumed it would create a new one if it didn't exist. Works wonderfully otherwise, thank you!!

**Comment by yriveiro** [comment]
+1 in atom 1.0.2

**Comment by mbugbee** [comment]
+1

**Comment by joe-vonlay** [comment]
+1

**Comment by p4t5h3** [comment]
Having the same issue in Atom 1.1.0

**Comment by DWiechert** [comment]
Same issue on Ubuntu.

**Comment by tugrul** [comment]
+1

Atom 1.3.2, Win10

**Comment by wuzhao** [comment]
+1

Atom 1.6.0 OSX EI Capitan 10.11.4

**Comment by seesarahcode** [comment]
+1 

Atom 1.6.1, OS X El Capitan 10.11.2

**Comment by wylie** [comment]
+1

```
TypeError: Cannot read property '0' of undefined
    at Object.module.exports.move (/Users/wylie/.atom/packages/move-panes/lib/move-panes.coffee:31:6)
    at Object.module.exports.moveDown (/Users/wylie/.atom/packages/move-panes/lib/move-panes.coffee:14:17)
    at atom-workspace.<anonymous> (/Users/wylie/.atom/packages/move-panes/lib/move-panes.coffee:6:69)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
- Atom 1.7.4
- Move Panes 0.2.0
- OS X El Capitan 10.11.3

**Comment by ghostsquad** [comment]
+1 

```
**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.6
**Thrown From**: [move-panes](https://github.com/santip/move-panes) package, v0.2.0
```

### Stack Trace

```
Uncaught TypeError: Cannot read property '0' of undefined


At /Users/wes/.atom/packages/move-panes/lib/move-panes.coffee:31

TypeError: Cannot read property '0' of undefined
    at Object.module.exports.move (/Users/wes/.atom/packages/move-panes/lib/move-panes.coffee:31:6)
    at Object.module.exports.moveRight (/Users/wes/.atom/packages/move-panes/lib/move-panes.coffee:11:18)
    at atom-workspace.atom.commands.add.move-panes:move-right (/Users/wes/.atom/packages/move-panes/lib/move-panes.coffee:4:70)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/wes/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Users/wes/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/wes/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/wes/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Users/wes/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Users/wes/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -3:19 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -3:18.4.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -3:15.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:15.2.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -3:14.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:11.4.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:57.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:46.3.0 editor:select-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -0:43.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:39.8.0 editor:select-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -0:36.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.7.0 move-panes:move-right (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-gfm",
      "linter-htmlhint"
    ],
    "themes": [
      "seti-ui",
      "monokai-seti"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
activate-power-mode, v0.7.0
atom-beautify, v0.29.10
atom-python-test, v0.2.1
auto-detect-indentation, v1.1.0
autoclose-html, v0.23.0
autocomplete-python, v1.8.4
autocomplete-ruby, v0.1.0
git-log, v0.4.1
highlight-selected, v0.11.2
language-markdown, v0.15.0
linter, v1.11.14
linter-csslint, v1.3.2
linter-haproxy, v0.2.2
linter-js-yaml, v1.2.5
linter-jshint, v2.1.0
linter-pep8, v1.3.0
linter-py, v1.0.1
linter-pylint, v1.2.1
linter-ruby, v1.2.2
linter-sass-lint, v1.6.1
linter-tidy, v2.1.1
minimap, v4.24.7
monokai-seti, v0.7.0
move-panes, v0.2.0
open-recent, v5.0.0
pigments, v0.31.2
python-tools, v0.6.8
qolor, v0.2.2
seti-ui, v1.3.1

# Dev
No dev packages
```

**Comment by AnthonyJacob** [comment]
Everything command that does something to panes / windows crashes - most of the time silently ( in other words nothing happens if I do spc-[1-9], spc-w-* ).
