### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPanes' of undefined

### ISSUE THREAD

**Issue by manisenkov** [santip/move-panes#5]
[Enter steps to reproduce below:]

1. Open two panes, each contains one tab.
2. Try to move one of tabs to other pane; it supposed to just close pane, that will be empty, but I got exception instead.

**Atom Version**: 0.186.0
**System**: Mac OS X 10.10.2
**Thrown From**: [move-panes](https://github.com/santip/move-panes) package, v0.1.2

### Stack Trace

Uncaught TypeError: Cannot read property 'getPanes' of undefined

```
At /Users/manisenkov/.atom/packages/move-panes/lib/move-panes.coffee:58

TypeError: Cannot read property 'getPanes' of undefined
  at Object.module.exports.getRelativePane (/Users/manisenkov/.atom/packages/move-panes/lib/move-panes.coffee:58:33)
  at Object.module.exports.move (/Users/manisenkov/.atom/packages/move-panes/lib/move-panes.coffee:33:17)
  at Object.module.exports.moveLeft (/Users/manisenkov/.atom/packages/move-panes/lib/move-panes.coffee:12:17)
  at atom-workspace.<anonymous> (/Users/manisenkov/.atom/packages/move-panes/lib/move-panes.coffee:5:60)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```

### Commands

```
     -0:52.3 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:52.3 core:cancel (atom-text-editor.editor.is-focused)
  6x -0:40.0 core:close (atom-text-editor.editor.is-focused)
     -0:17.4 tree-view:toggle (atom-text-editor.editor)
     -0:10.4 window:focus-pane-on-left (atom-text-editor.editor)
     -0:07.2 pane:split-left (atom-text-editor.editor.is-focused)
     -0:04.7 pane:close (atom-text-editor.editor.is-focused)
     -0:01.0 move-panes:move-left (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-lint, v0.20.1
editorconfig, v0.3.0
linter, v0.12.0
minimap, v4.5.0
move-panes, v0.1.2
project-manager, v1.15.5
seti-syntax, v0.3.3
seti-ui, v0.6.3

# Dev
No dev packages
```

**Comment by crucialfelix** [comment]
Same here. This has been going on for a while now actually.

I have many tabs each pane.

thanks !

```
/Users/crucial/.atom/packages/move-panes/lib/move-panes.coffee:58
Hide Stack Trace
TypeError: Cannot read property 'getPanes' of undefined
  at Object.module.exports.getRelativePane (/Users/crucial/.atom/packages/move-panes/lib/move-panes.coffee:58:33)
  at Object.module.exports.move (/Users/crucial/.atom/packages/move-panes/lib/move-panes.coffee:33:17)
  at Object.module.exports.moveLeft (/Users/crucial/.atom/packages/move-panes/lib/move-panes.coffee:12:17)
  at atom-workspace.<anonymous> (/Users/crucial/.atom/packages/move-panes/lib/move-panes.coffee:5:60)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:246:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:159:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:75:30)
  at EventEmitter.emit (events.js:116:17)
```

**Comment by damien-m** [comment]
I get this issue when trying to move a tab either left or top, when I'm in the left-most or top-most pane in a group.

**Comment by mikeerickson** [comment]
+1

**Comment by aaronshaver** [comment]
+1
